-- Seed das 980 figurinhas do álbum FIFA Copa do Mundo 2026 (Panini)
-- Idempotente: pode rodar de novo sem duplicar.
insert into public.stickers (id, team_code, team_name, number, name, kind) values
('00','FWC','Especiais',0,'Panini Logo','special'),
('FWC1','FWC','Especiais',1,'Official Emblem','special'),
('FWC2','FWC','Especiais',2,'Official Emblem','special'),
('FWC3','FWC','Especiais',3,'Official Mascots','special'),
('FWC4','FWC','Especiais',4,'Official Slogan','special'),
('FWC5','FWC','Especiais',5,'Official Ball','special'),
('FWC6','FWC','Especiais',6,'Canada','special'),
('FWC7','FWC','Especiais',7,'Mexico','special'),
('FWC8','FWC','Especiais',8,'USA','special'),
('FWC9','FWC','Especiais',9,'Italy 1934','special'),
('FWC10','FWC','Especiais',10,'Uruguay 1950','special'),
('FWC11','FWC','Especiais',11,'West Germany 1954','special'),
('FWC12','FWC','Especiais',12,'Brazil 1962','special'),
('FWC13','FWC','Especiais',13,'West Germany 1974','special'),
('FWC14','FWC','Especiais',14,'Argentina 1986','special'),
('FWC15','FWC','Especiais',15,'Brazil 1994','special'),
('FWC16','FWC','Especiais',16,'Brazil 2002','special'),
('FWC17','FWC','Especiais',17,'Italy 2006','special'),
('FWC18','FWC','Especiais',18,'Germany 2014','special'),
('FWC19','FWC','Especiais',19,'Argentina 2022','special'),
('ALG1','ALG','Argélia',1,'Team Logo','logo'),
('ALG2','ALG','Argélia',2,'Alexis Guendouz','player'),
('ALG3','ALG','Argélia',3,'Ramy Bensebaini','player'),
('ALG4','ALG','Argélia',4,'Youcef Atal','player'),
('ALG5','ALG','Argélia',5,'Rayan Aït-Nouri','player'),
('ALG6','ALG','Argélia',6,'Mohamed Amine Tougai','player'),
('ALG7','ALG','Argélia',7,'Aïssa Mandi','player'),
('ALG8','ALG','Argélia',8,'Ismael Bennacer','player'),
('ALG9','ALG','Argélia',9,'Houssem Aquar','player'),
('ALG10','ALG','Argélia',10,'Hicham Boudaoui','player'),
('ALG11','ALG','Argélia',11,'Ramiz Zerrouki','player'),
('ALG12','ALG','Argélia',12,'Nabil Bentalab','player'),
('ALG13','ALG','Argélia',13,'Team Photo','photo'),
('ALG14','ALG','Argélia',14,'Farés Chaibi','player'),
('ALG15','ALG','Argélia',15,'Riyad Mahrez','player'),
('ALG16','ALG','Argélia',16,'Said Benrahma','player'),
('ALG17','ALG','Argélia',17,'Anis Hadj Moussa','player'),
('ALG18','ALG','Argélia',18,'Amine Gouiri','player'),
('ALG19','ALG','Argélia',19,'Baghdad Bounedjah','player'),
('ALG20','ALG','Argélia',20,'Mohammed Amoura','player'),
('ARG1','ARG','Argentina',1,'Team Logo','logo'),
('ARG2','ARG','Argentina',2,'Emiliano Martinez','player'),
('ARG3','ARG','Argentina',3,'Nahuel Molina','player'),
('ARG4','ARG','Argentina',4,'Cristian Romero','player'),
('ARG5','ARG','Argentina',5,'Nicolas Otamendi','player'),
('ARG6','ARG','Argentina',6,'Nicolas Tagliafico','player'),
('ARG7','ARG','Argentina',7,'Leonardo Balerdi','player'),
('ARG8','ARG','Argentina',8,'Enzo Fernandez','player'),
('ARG9','ARG','Argentina',9,'Alexis Mac Allister','player'),
('ARG10','ARG','Argentina',10,'Rodrigo De Paul','player'),
('ARG11','ARG','Argentina',11,'Exequiel Palacios','player'),
('ARG12','ARG','Argentina',12,'Leandro Paredes','player'),
('ARG13','ARG','Argentina',13,'Team Photo','photo'),
('ARG14','ARG','Argentina',14,'Nico Paz','player'),
('ARG15','ARG','Argentina',15,'Franco Mastantuono','player'),
('ARG16','ARG','Argentina',16,'Nico Gonzalez','player'),
('ARG17','ARG','Argentina',17,'Lionel Messi','player'),
('ARG18','ARG','Argentina',18,'Lautaro Martinez','player'),
('ARG19','ARG','Argentina',19,'Julian Alvarez','player'),
('ARG20','ARG','Argentina',20,'Giuliano Simeone','player'),
('AUS1','AUS','Austrália',1,'Team Logo','logo'),
('AUS2','AUS','Austrália',2,'Mathew Ryan','player'),
('AUS3','AUS','Austrália',3,'Joe Gauci','player'),
('AUS4','AUS','Austrália',4,'Harry Souttar','player'),
('AUS5','AUS','Austrália',5,'Alessandro Circati','player'),
('AUS6','AUS','Austrália',6,'Jordan Bos','player'),
('AUS7','AUS','Austrália',7,'Aziz Behich','player'),
('AUS8','AUS','Austrália',8,'Cameron Burgess','player'),
('AUS9','AUS','Austrália',9,'Lewis Miller','player'),
('AUS10','AUS','Austrália',10,'Milos Degenek','player'),
('AUS11','AUS','Austrália',11,'Jackson Irvine','player'),
('AUS12','AUS','Austrália',12,'Riley McGree','player'),
('AUS13','AUS','Austrália',13,'Team Photo','photo'),
('AUS14','AUS','Austrália',14,'Aiden O''Neill','player'),
('AUS15','AUS','Austrália',15,'Connor Metcalfe','player'),
('AUS16','AUS','Austrália',16,'Patrick Yazbek','player'),
('AUS17','AUS','Austrália',17,'Craig Goodwin','player'),
('AUS18','AUS','Austrália',18,'Kusini Vengi','player'),
('AUS19','AUS','Austrália',19,'Nestory Irankunda','player'),
('AUS20','AUS','Austrália',20,'Mohamed Touré','player'),
('AUT1','AUT','Áustria',1,'Team Logo','logo'),
('AUT2','AUT','Áustria',2,'Alexander Schlager','player'),
('AUT3','AUT','Áustria',3,'Patrick Pentz','player'),
('AUT4','AUT','Áustria',4,'David Alaba','player'),
('AUT5','AUT','Áustria',5,'Kevin Danso','player'),
('AUT6','AUT','Áustria',6,'Philipp Lienhart','player'),
('AUT7','AUT','Áustria',7,'Stefan Posch','player'),
('AUT8','AUT','Áustria',8,'Phillipp Mwene','player'),
('AUT9','AUT','Áustria',9,'Alexander Prass','player'),
('AUT10','AUT','Áustria',10,'Xaver Schlager','player'),
('AUT11','AUT','Áustria',11,'Marcel Sabitzer','player'),
('AUT12','AUT','Áustria',12,'Konrad Laimer','player'),
('AUT13','AUT','Áustria',13,'Team Photo','photo'),
('AUT14','AUT','Áustria',14,'Florian Grillitsch','player'),
('AUT15','AUT','Áustria',15,'Nicolas Seiwald','player'),
('AUT16','AUT','Áustria',16,'Romano Schmid','player'),
('AUT17','AUT','Áustria',17,'Patrick Wimmer','player'),
('AUT18','AUT','Áustria',18,'Christoph Baumgartner','player'),
('AUT19','AUT','Áustria',19,'Michael Gregoritsch','player'),
('AUT20','AUT','Áustria',20,'Marko Arnautović','player'),
('BEL1','BEL','Bélgica',1,'Team Logo','logo'),
('BEL2','BEL','Bélgica',2,'Thibaut Courtois','player'),
('BEL3','BEL','Bélgica',3,'Arthur Theate','player'),
('BEL4','BEL','Bélgica',4,'Timothy Castagne','player'),
('BEL5','BEL','Bélgica',5,'Zeno Debast','player'),
('BEL6','BEL','Bélgica',6,'Brandon Mechele','player'),
('BEL7','BEL','Bélgica',7,'Maxim De Cuyper','player'),
('BEL8','BEL','Bélgica',8,'Thomas Meunier','player'),
('BEL9','BEL','Bélgica',9,'Youri Tielemans','player'),
('BEL10','BEL','Bélgica',10,'Amadou Onana','player'),
('BEL11','BEL','Bélgica',11,'Nicolas Raskin','player'),
('BEL12','BEL','Bélgica',12,'Alexis Saelemaekers','player'),
('BEL13','BEL','Bélgica',13,'Team Photo','photo'),
('BEL14','BEL','Bélgica',14,'Hans Vanaken','player'),
('BEL15','BEL','Bélgica',15,'Kevin De Bruyne','player'),
('BEL16','BEL','Bélgica',16,'Jérémy Doku','player'),
('BEL17','BEL','Bélgica',17,'Charles De Ketelaere','player'),
('BEL18','BEL','Bélgica',18,'Leandro Trossard','player'),
('BEL19','BEL','Bélgica',19,'Loïs Openda','player'),
('BEL20','BEL','Bélgica',20,'Romelu Lukaku','player'),
('BIH1','BIH','Bósnia e Herzegovina',1,'Team Logo','logo'),
('BIH2','BIH','Bósnia e Herzegovina',2,'Nikola Vasilj','player'),
('BIH3','BIH','Bósnia e Herzegovina',3,'Amer Dedic','player'),
('BIH4','BIH','Bósnia e Herzegovina',4,'Sead Kolasinac','player'),
('BIH5','BIH','Bósnia e Herzegovina',5,'Tarik Muharemovic','player'),
('BIH6','BIH','Bósnia e Herzegovina',6,'Nihad Mujakic','player'),
('BIH7','BIH','Bósnia e Herzegovina',7,'Nikola Katic','player'),
('BIH8','BIH','Bósnia e Herzegovina',8,'Amir Hadziahmetovic','player'),
('BIH9','BIH','Bósnia e Herzegovina',9,'Benjamin Tahirovic','player'),
('BIH10','BIH','Bósnia e Herzegovina',10,'Armin Gigovic','player'),
('BIH11','BIH','Bósnia e Herzegovina',11,'Ivan Sunjic','player'),
('BIH12','BIH','Bósnia e Herzegovina',12,'Ivan Basic','player'),
('BIH13','BIH','Bósnia e Herzegovina',13,'Team Photo','photo'),
('BIH14','BIH','Bósnia e Herzegovina',14,'Dzenis Burnic','player'),
('BIH15','BIH','Bósnia e Herzegovina',15,'Esmir Bajraktarevic','player'),
('BIH16','BIH','Bósnia e Herzegovina',16,'Amar Memic','player'),
('BIH17','BIH','Bósnia e Herzegovina',17,'Ermedin Demirovic','player'),
('BIH18','BIH','Bósnia e Herzegovina',18,'Edin Dzeko','player'),
('BIH19','BIH','Bósnia e Herzegovina',19,'Samed Bazdar','player'),
('BIH20','BIH','Bósnia e Herzegovina',20,'Haris Tabakovic','player'),
('BRA1','BRA','Brasil',1,'Team Logo','logo'),
('BRA2','BRA','Brasil',2,'Alisson','player'),
('BRA3','BRA','Brasil',3,'Bento','player'),
('BRA4','BRA','Brasil',4,'Marquinhos','player'),
('BRA5','BRA','Brasil',5,'Éder Militão','player'),
('BRA6','BRA','Brasil',6,'Gabriel Magalhães','player'),
('BRA7','BRA','Brasil',7,'Danilo','player'),
('BRA8','BRA','Brasil',8,'Wesley','player'),
('BRA9','BRA','Brasil',9,'Lucas Paquetá','player'),
('BRA10','BRA','Brasil',10,'Casemiro','player'),
('BRA11','BRA','Brasil',11,'Bruno Guimarães','player'),
('BRA12','BRA','Brasil',12,'Luiz Henrique','player'),
('BRA13','BRA','Brasil',13,'Team Photo','photo'),
('BRA14','BRA','Brasil',14,'Vinicius Júnior','player'),
('BRA15','BRA','Brasil',15,'Rodrygo','player'),
('BRA16','BRA','Brasil',16,'João Pedro','player'),
('BRA17','BRA','Brasil',17,'Matheus Cunha','player'),
('BRA18','BRA','Brasil',18,'Gabriel Martinelli','player'),
('BRA19','BRA','Brasil',19,'Raphinha','player'),
('BRA20','BRA','Brasil',20,'Estévão','player'),
('CAN1','CAN','Canadá',1,'Team Logo','logo'),
('CAN2','CAN','Canadá',2,'Dayne St.Clair','player'),
('CAN3','CAN','Canadá',3,'Alphonso Davies','player'),
('CAN4','CAN','Canadá',4,'Alistair Johnston','player'),
('CAN5','CAN','Canadá',5,'Samuel Adekugbe','player'),
('CAN6','CAN','Canadá',6,'Riche Larvea','player'),
('CAN7','CAN','Canadá',7,'Derek Cornelius','player'),
('CAN8','CAN','Canadá',8,'Moïse Bombito','player'),
('CAN9','CAN','Canadá',9,'Kamal Miller','player'),
('CAN10','CAN','Canadá',10,'Stephen Eustáquio','player'),
('CAN11','CAN','Canadá',11,'Ismaël Koné','player'),
('CAN12','CAN','Canadá',12,'Jonathan Osorio','player'),
('CAN13','CAN','Canadá',13,'Team Photo','photo'),
('CAN14','CAN','Canadá',14,'Jacob Shaffelburg','player'),
('CAN15','CAN','Canadá',15,'Mathieu Choinière','player'),
('CAN16','CAN','Canadá',16,'Niko Sigur','player'),
('CAN17','CAN','Canadá',17,'Tajon Buchanan','player'),
('CAN18','CAN','Canadá',18,'Liam Millar','player'),
('CAN19','CAN','Canadá',19,'Cyle Larin','player'),
('CAN20','CAN','Canadá',20,'Jonathan David','player'),
('CPV1','CPV','Cabo Verde',1,'Team Logo','logo'),
('CPV2','CPV','Cabo Verde',2,'Vozinha','player'),
('CPV3','CPV','Cabo Verde',3,'Logan Costa','player'),
('CPV4','CPV','Cabo Verde',4,'Pico','player'),
('CPV5','CPV','Cabo Verde',5,'Diney','player'),
('CPV6','CPV','Cabo Verde',6,'Steven Moreira','player'),
('CPV7','CPV','Cabo Verde',7,'Wagner Pina','player'),
('CPV8','CPV','Cabo Verde',8,'Joao Paulo','player'),
('CPV9','CPV','Cabo Verde',9,'Yannick Semedo','player'),
('CPV10','CPV','Cabo Verde',10,'Kevin Pina','player'),
('CPV11','CPV','Cabo Verde',11,'Patrick Andrade','player'),
('CPV12','CPV','Cabo Verde',12,'Jamiro Monteiro','player'),
('CPV13','CPV','Cabo Verde',13,'Team Photo','photo'),
('CPV14','CPV','Cabo Verde',14,'Deroy Duarte','player'),
('CPV15','CPV','Cabo Verde',15,'Garry Rodrigues','player'),
('CPV16','CPV','Cabo Verde',16,'Jovane Cabral','player'),
('CPV17','CPV','Cabo Verde',17,'Ryan Mendes','player'),
('CPV18','CPV','Cabo Verde',18,'Dailon Livramento','player'),
('CPV19','CPV','Cabo Verde',19,'Willy Semedo','player'),
('CPV20','CPV','Cabo Verde',20,'Bebe','player'),
('COL1','COL','Colômbia',1,'Team Logo','logo'),
('COL2','COL','Colômbia',2,'Camilo Vargas','player'),
('COL3','COL','Colômbia',3,'David Ospina','player'),
('COL4','COL','Colômbia',4,'Dávinson Sánchez','player'),
('COL5','COL','Colômbia',5,'Yerry Mina','player'),
('COL6','COL','Colômbia',6,'Daniel Munoz','player'),
('COL7','COL','Colômbia',7,'Johan Mojica','player'),
('COL8','COL','Colômbia',8,'Jhon Lucumí','player'),
('COL9','COL','Colômbia',9,'Santiago Arias','player'),
('COL10','COL','Colômbia',10,'Jefferson Lerma','player'),
('COL11','COL','Colômbia',11,'Kevin Castaño','player'),
('COL12','COL','Colômbia',12,'Richard Rios','player'),
('COL13','COL','Colômbia',13,'Team Photo','photo'),
('COL14','COL','Colômbia',14,'James Rodriguez','player'),
('COL15','COL','Colômbia',15,'Juan Fernando Quintero','player'),
('COL16','COL','Colômbia',16,'Jorge Carrascal','player'),
('COL17','COL','Colômbia',17,'Jon Arias','player'),
('COL18','COL','Colômbia',18,'Jhon Cordova','player'),
('COL19','COL','Colômbia',19,'Luis Suarez','player'),
('COL20','COL','Colômbia',20,'Luis Diaz','player'),
('COD1','COD','Congo (RDC)',1,'Team Logo','logo'),
('COD2','COD','Congo (RDC)',2,'Lionel Mpasi','player'),
('COD3','COD','Congo (RDC)',3,'Aaron Wan-Bissaka','player'),
('COD4','COD','Congo (RDC)',4,'Axel Tuanzebe','player'),
('COD5','COD','Congo (RDC)',5,'Arthur Masuaku','player'),
('COD6','COD','Congo (RDC)',6,'Chancel Mbemba','player'),
('COD7','COD','Congo (RDC)',7,'Joris Kayembe','player'),
('COD8','COD','Congo (RDC)',8,'Charles Pickel','player'),
('COD9','COD','Congo (RDC)',9,'Ngal''ayel Mukau','player'),
('COD10','COD','Congo (RDC)',10,'Edo Kayembe','player'),
('COD11','COD','Congo (RDC)',11,'Samuel Moutoussamy','player'),
('COD12','COD','Congo (RDC)',12,'Noah Sadiki','player'),
('COD13','COD','Congo (RDC)',13,'Team Photo','photo'),
('COD14','COD','Congo (RDC)',14,'Théo Bongonda','player'),
('COD15','COD','Congo (RDC)',15,'Meschak Elia','player'),
('COD16','COD','Congo (RDC)',16,'Yoane Wissa','player'),
('COD17','COD','Congo (RDC)',17,'Brian Cipenga','player'),
('COD18','COD','Congo (RDC)',18,'Fiston Mayele','player'),
('COD19','COD','Congo (RDC)',19,'Cédric Bakambu','player'),
('COD20','COD','Congo (RDC)',20,'Nathanaël Mbuku','player'),
('CRO1','CRO','Croácia',1,'Team Logo','logo'),
('CRO2','CRO','Croácia',2,'Dominik Livaković','player'),
('CRO3','CRO','Croácia',3,'Duje Caleta-Car','player'),
('CRO4','CRO','Croácia',4,'Josko Gvardiol','player'),
('CRO5','CRO','Croácia',5,'Josip Stanišić','player'),
('CRO6','CRO','Croácia',6,'Luka Vušković','player'),
('CRO7','CRO','Croácia',7,'Josip Sutalo','player'),
('CRO8','CRO','Croácia',8,'Kristijan Jakic','player'),
('CRO9','CRO','Croácia',9,'Luka Modrić','player'),
('CRO10','CRO','Croácia',10,'Mateo Kovacic','player'),
('CRO11','CRO','Croácia',11,'Martin Baturina','player'),
('CRO12','CRO','Croácia',12,'Lovro Majer','player'),
('CRO13','CRO','Croácia',13,'Team Photo','photo'),
('CRO14','CRO','Croácia',14,'Mario Pasalic','player'),
('CRO15','CRO','Croácia',15,'Petar Sucic','player'),
('CRO16','CRO','Croácia',16,'Ivan Perišić','player'),
('CRO17','CRO','Croácia',17,'Marco Pasalic','player'),
('CRO18','CRO','Croácia',18,'Ante Budimir','player'),
('CRO19','CRO','Croácia',19,'Andrej Kramarić','player'),
('CRO20','CRO','Croácia',20,'Franjo Ivanovic','player'),
('CUW1','CUW','Curaçao',1,'Team Logo','logo'),
('CUW2','CUW','Curaçao',2,'Eloy Room','player'),
('CUW3','CUW','Curaçao',3,'Armando Obispo','player'),
('CUW4','CUW','Curaçao',4,'Sherel Floranus','player'),
('CUW5','CUW','Curaçao',5,'Jurien Gaari','player'),
('CUW6','CUW','Curaçao',6,'Joshua Brenet','player'),
('CUW7','CUW','Curaçao',7,'Roshon Van Eijma','player'),
('CUW8','CUW','Curaçao',8,'Shurandy Sambo','player'),
('CUW9','CUW','Curaçao',9,'Livano Comenencia','player'),
('CUW10','CUW','Curaçao',10,'Godfried Roemeratoe','player'),
('CUW11','CUW','Curaçao',11,'Juninho Bacuna','player'),
('CUW12','CUW','Curaçao',12,'Leandro Bacuna','player'),
('CUW13','CUW','Curaçao',13,'Team Photo','photo'),
('CUW14','CUW','Curaçao',14,'Tahith Chong','player'),
('CUW15','CUW','Curaçao',15,'Kenji Gorre','player'),
('CUW16','CUW','Curaçao',16,'Jearl Margaritha','player'),
('CUW17','CUW','Curaçao',17,'Jurgen Locadia','player'),
('CUW18','CUW','Curaçao',18,'Jeremy Antonisse','player'),
('CUW19','CUW','Curaçao',19,'Gervane Kastaneer','player'),
('CUW20','CUW','Curaçao',20,'Sontje Hansen','player'),
('CZE1','CZE','Tchéquia',1,'Team Logo','logo'),
('CZE2','CZE','Tchéquia',2,'Matej Kovar','player'),
('CZE3','CZE','Tchéquia',3,'Jindrich Stanek','player'),
('CZE4','CZE','Tchéquia',4,'Ladislav Krejci','player'),
('CZE5','CZE','Tchéquia',5,'Vladimir Coufal','player'),
('CZE6','CZE','Tchéquia',6,'Jaroslav Zeleny','player'),
('CZE7','CZE','Tchéquia',7,'Tomas Holes','player'),
('CZE8','CZE','Tchéquia',8,'David Zima','player'),
('CZE9','CZE','Tchéquia',9,'Michal Sadilek','player'),
('CZE10','CZE','Tchéquia',10,'Lukas Provod','player'),
('CZE11','CZE','Tchéquia',11,'Lukas Cerv','player'),
('CZE12','CZE','Tchéquia',12,'Tomas Soucek','player'),
('CZE13','CZE','Tchéquia',13,'Team Photo','photo'),
('CZE14','CZE','Tchéquia',14,'Pavel Sulc','player'),
('CZE15','CZE','Tchéquia',15,'Matej Vydra','player'),
('CZE16','CZE','Tchéquia',16,'Vasil Kusej','player'),
('CZE17','CZE','Tchéquia',17,'Tomas Chory','player'),
('CZE18','CZE','Tchéquia',18,'Vaclav Cerny','player'),
('CZE19','CZE','Tchéquia',19,'Adam Hlozek','player'),
('CZE20','CZE','Tchéquia',20,'Patrik Schick','player'),
('ECU1','ECU','Equador',1,'Team Logo','logo'),
('ECU2','ECU','Equador',2,'Hernán Galíndez','player'),
('ECU3','ECU','Equador',3,'Gonzalo Valle','player'),
('ECU4','ECU','Equador',4,'Piero Hincapié','player'),
('ECU5','ECU','Equador',5,'Pervis Estupiñán','player'),
('ECU6','ECU','Equador',6,'Willian Pacho','player'),
('ECU7','ECU','Equador',7,'Ángelo Preciado','player'),
('ECU8','ECU','Equador',8,'Joel Ordóñez','player'),
('ECU9','ECU','Equador',9,'Moises Caicedo','player'),
('ECU10','ECU','Equador',10,'Alan Franco','player'),
('ECU11','ECU','Equador',11,'Kendry Paez','player'),
('ECU12','ECU','Equador',12,'Pedro Vite','player'),
('ECU13','ECU','Equador',13,'Team Photo','photo'),
('ECU14','ECU','Equador',14,'John Veboah','player'),
('ECU15','ECU','Equador',15,'Leonardo Campana','player'),
('ECU16','ECU','Equador',16,'Gonzalo Plata','player'),
('ECU17','ECU','Equador',17,'Nilson Angulo','player'),
('ECU18','ECU','Equador',18,'Alan Minda','player'),
('ECU19','ECU','Equador',19,'Kevin Rodriguez','player'),
('ECU20','ECU','Equador',20,'Enner Valencia','player'),
('EGY1','EGY','Egito',1,'Team Logo','logo'),
('EGY2','EGY','Egito',2,'Mohamed El Shenawy','player'),
('EGY3','EGY','Egito',3,'Mohamed Hany','player'),
('EGY4','EGY','Egito',4,'Mohamed Hamdy','player'),
('EGY5','EGY','Egito',5,'Yasser Ibrahim','player'),
('EGY6','EGY','Egito',6,'Khaled Sobhi','player'),
('EGY7','EGY','Egito',7,'Ramy Rabia','player'),
('EGY8','EGY','Egito',8,'Hossam Abdelmaguid','player'),
('EGY9','EGY','Egito',9,'Ahmed Fatouh','player'),
('EGY10','EGY','Egito',10,'Marwan Attia','player'),
('EGY11','EGY','Egito',11,'Zizo','player'),
('EGY12','EGY','Egito',12,'Hamdy Fathy','player'),
('EGY13','EGY','Egito',13,'Team Photo','photo'),
('EGY14','EGY','Egito',14,'Mohamed Lasheen','player'),
('EGY15','EGY','Egito',15,'Emam Ashour','player'),
('EGY16','EGY','Egito',16,'Osama Faisal','player'),
('EGY17','EGY','Egito',17,'Mohamed Salah','player'),
('EGY18','EGY','Egito',18,'Mostafa Mohamed','player'),
('EGY19','EGY','Egito',19,'Trezeguet','player'),
('EGY20','EGY','Egito',20,'Omar Marmoush','player'),
('ENG1','ENG','Inglaterra',1,'Team Logo','logo'),
('ENG2','ENG','Inglaterra',2,'Jordan Pickford','player'),
('ENG3','ENG','Inglaterra',3,'John Stones','player'),
('ENG4','ENG','Inglaterra',4,'Marc Guéhi','player'),
('ENG5','ENG','Inglaterra',5,'Ezri Konsa','player'),
('ENG6','ENG','Inglaterra',6,'Trent Alexander-Arnold','player'),
('ENG7','ENG','Inglaterra',7,'Reece James','player'),
('ENG8','ENG','Inglaterra',8,'Dan Burn','player'),
('ENG9','ENG','Inglaterra',9,'Jordan Henderson','player'),
('ENG10','ENG','Inglaterra',10,'Declan Rice','player'),
('ENG11','ENG','Inglaterra',11,'Jude Bellingham','player'),
('ENG12','ENG','Inglaterra',12,'Cole Palmer','player'),
('ENG13','ENG','Inglaterra',13,'Team Photo','photo'),
('ENG14','ENG','Inglaterra',14,'Morgan Rogers','player'),
('ENG15','ENG','Inglaterra',15,'Anthony Gordon','player'),
('ENG16','ENG','Inglaterra',16,'Phil Foden','player'),
('ENG17','ENG','Inglaterra',17,'Bukayo Saka','player'),
('ENG18','ENG','Inglaterra',18,'Harry Kane','player'),
('ENG19','ENG','Inglaterra',19,'Marcus Rashford','player'),
('ENG20','ENG','Inglaterra',20,'Ollie Watkins','player'),
('FRA1','FRA','França',1,'Team Logo','logo'),
('FRA2','FRA','França',2,'Mike Maignan','player'),
('FRA3','FRA','França',3,'Theo Hernandez','player'),
('FRA4','FRA','França',4,'William Saliba','player'),
('FRA5','FRA','França',5,'Jules Kounde','player'),
('FRA6','FRA','França',6,'Ibrahima Konate','player'),
('FRA7','FRA','França',7,'Dayot Upamecano','player'),
('FRA8','FRA','França',8,'Lucas Digne','player'),
('FRA9','FRA','França',9,'Aurélien Tchouaméni','player'),
('FRA10','FRA','França',10,'Eduardo Camavinga','player'),
('FRA11','FRA','França',11,'Manu Kone','player'),
('FRA12','FRA','França',12,'Adrien Rabiot','player'),
('FRA13','FRA','França',13,'Team Photo','photo'),
('FRA14','FRA','França',14,'Michael Olise','player'),
('FRA15','FRA','França',15,'Ousmane Dembele','player'),
('FRA16','FRA','França',16,'Bradley Barcola','player'),
('FRA17','FRA','França',17,'Désiré Doué','player'),
('FRA18','FRA','França',18,'Kingsley Coman','player'),
('FRA19','FRA','França',19,'Hugo Ekitike','player'),
('FRA20','FRA','França',20,'Kylian Mbappe','player'),
('GER1','GER','Alemanha',1,'Team Logo','logo'),
('GER2','GER','Alemanha',2,'Marc-André ter Stegen','player'),
('GER3','GER','Alemanha',3,'Jonathan Tah','player'),
('GER4','GER','Alemanha',4,'David Raum','player'),
('GER5','GER','Alemanha',5,'Nico Schlotterbeck','player'),
('GER6','GER','Alemanha',6,'Antonio Rüdiger','player'),
('GER7','GER','Alemanha',7,'Waldemar Anton','player'),
('GER8','GER','Alemanha',8,'Ridle Baku','player'),
('GER9','GER','Alemanha',9,'Maximilian Mittelstadt','player'),
('GER10','GER','Alemanha',10,'Joshua Kimmich','player'),
('GER11','GER','Alemanha',11,'Florian Wirtz','player'),
('GER12','GER','Alemanha',12,'Felix Nmecha','player'),
('GER13','GER','Alemanha',13,'Team Photo','photo'),
('GER14','GER','Alemanha',14,'Leon Goretzka','player'),
('GER15','GER','Alemanha',15,'Jamal Musiala','player'),
('GER16','GER','Alemanha',16,'Serge Gnabry','player'),
('GER17','GER','Alemanha',17,'Kai Havertz','player'),
('GER18','GER','Alemanha',18,'Leroy Sane','player'),
('GER19','GER','Alemanha',19,'Karim Adeyemi','player'),
('GER20','GER','Alemanha',20,'Nick Woltemade','player'),
('GHA1','GHA','Gana',1,'Team Logo','logo'),
('GHA2','GHA','Gana',2,'Lawrence Ati Zigi','player'),
('GHA3','GHA','Gana',3,'Tariq Lamptey','player'),
('GHA4','GHA','Gana',4,'Mohammed Salisu','player'),
('GHA5','GHA','Gana',5,'Alidu Seidu','player'),
('GHA6','GHA','Gana',6,'Alexander Djiku','player'),
('GHA7','GHA','Gana',7,'Gideon Mensah','player'),
('GHA8','GHA','Gana',8,'Caleb Yirenkyi','player'),
('GHA9','GHA','Gana',9,'Abdul Issahaku Fatawu','player'),
('GHA10','GHA','Gana',10,'Thomas Partey','player'),
('GHA11','GHA','Gana',11,'Salis Abdul Samed','player'),
('GHA12','GHA','Gana',12,'Kamaldeen Sulemana','player'),
('GHA13','GHA','Gana',13,'Team Photo','photo'),
('GHA14','GHA','Gana',14,'Mohammed Kudus','player'),
('GHA15','GHA','Gana',15,'Inaki Williams','player'),
('GHA16','GHA','Gana',16,'Jordan Ayew','player'),
('GHA17','GHA','Gana',17,'Andrew Ayew','player'),
('GHA18','GHA','Gana',18,'Joseph Paintsil','player'),
('GHA19','GHA','Gana',19,'Osman Bukari','player'),
('GHA20','GHA','Gana',20,'Antoine Semenyo','player'),
('HAI1','HAI','Haiti',1,'Team Logo','logo'),
('HAI2','HAI','Haiti',2,'Johny Placide','player'),
('HAI3','HAI','Haiti',3,'Carlens Arcus','player'),
('HAI4','HAI','Haiti',4,'Martin Expérience','player'),
('HAI5','HAI','Haiti',5,'Jean-Kevin Duverne','player'),
('HAI6','HAI','Haiti',6,'Ricardo Adé','player'),
('HAI7','HAI','Haiti',7,'Duke Lacroix','player'),
('HAI8','HAI','Haiti',8,'Garven Metusala','player'),
('HAI9','HAI','Haiti',9,'Hannes Delcroix','player'),
('HAI10','HAI','Haiti',10,'Leverton Pierre','player'),
('HAI11','HAI','Haiti',11,'Danley Jean Jacques','player'),
('HAI12','HAI','Haiti',12,'Jean-Ricner Bellegarde','player'),
('HAI13','HAI','Haiti',13,'Team Photo','photo'),
('HAI14','HAI','Haiti',14,'Christopher Attys','player'),
('HAI15','HAI','Haiti',15,'Derrick Etienne Jr','player'),
('HAI16','HAI','Haiti',16,'Josue Casimir','player'),
('HAI17','HAI','Haiti',17,'Ruben Providence','player'),
('HAI18','HAI','Haiti',18,'Duckens Nazon','player'),
('HAI19','HAI','Haiti',19,'Louicius Deedson','player'),
('HAI20','HAI','Haiti',20,'Frantzdy Pierrot','player'),
('IRN1','IRN','Irã',1,'Team Logo','logo'),
('IRN2','IRN','Irã',2,'Alireza Beiranvand','player'),
('IRN3','IRN','Irã',3,'Morteza Pouraliganji','player'),
('IRN4','IRN','Irã',4,'Ehsan Hajsafi','player'),
('IRN5','IRN','Irã',5,'Milad Mohammadi','player'),
('IRN6','IRN','Irã',6,'Shojae Khalilzadeh','player'),
('IRN7','IRN','Irã',7,'Ramin Rezaeian','player'),
('IRN8','IRN','Irã',8,'Hossein Kanaani','player'),
('IRN9','IRN','Irã',9,'Sadegh Moharrami','player'),
('IRN10','IRN','Irã',10,'Saleh Hardani','player'),
('IRN11','IRN','Irã',11,'Saeed Ezatolahi','player'),
('IRN12','IRN','Irã',12,'Saman Ghoddos','player'),
('IRN13','IRN','Irã',13,'Team Photo','photo'),
('IRN14','IRN','Irã',14,'Omid Noorafkan','player'),
('IRN15','IRN','Irã',15,'Roozbeh Cheshmi','player'),
('IRN16','IRN','Irã',16,'Mohammad Mohebi','player'),
('IRN17','IRN','Irã',17,'Sardar Azmoun','player'),
('IRN18','IRN','Irã',18,'Mehdi Taremi','player'),
('IRN19','IRN','Irã',19,'Alireza Jahanbakhsh','player'),
('IRN20','IRN','Irã',20,'Ali Gholizadeh','player'),
('IRQ1','IRQ','Iraque',1,'Team Logo','logo'),
('IRQ2','IRQ','Iraque',2,'Jalal Hassan','player'),
('IRQ3','IRQ','Iraque',3,'Rebin Sulaka','player'),
('IRQ4','IRQ','Iraque',4,'Hussein Ali','player'),
('IRQ5','IRQ','Iraque',5,'Akam Hashem','player'),
('IRQ6','IRQ','Iraque',6,'Merchas Doski','player'),
('IRQ7','IRQ','Iraque',7,'Zaid Tahseen','player'),
('IRQ8','IRQ','Iraque',8,'Manaf Younis','player'),
('IRQ9','IRQ','Iraque',9,'Zidane Iqbal','player'),
('IRQ10','IRQ','Iraque',10,'Amir Al-Ammari','player'),
('IRQ11','IRQ','Iraque',11,'Ibrahim Bayesh','player'),
('IRQ12','IRQ','Iraque',12,'Ali Jasim','player'),
('IRQ13','IRQ','Iraque',13,'Team Photo','photo'),
('IRQ14','IRQ','Iraque',14,'Youssef Amyn','player'),
('IRQ15','IRQ','Iraque',15,'Aimar Sher','player'),
('IRQ16','IRQ','Iraque',16,'Marko Farji','player'),
('IRQ17','IRQ','Iraque',17,'Osama Rashid','player'),
('IRQ18','IRQ','Iraque',18,'Ali Al-Hamadi','player'),
('IRQ19','IRQ','Iraque',19,'Aymen Hussein','player'),
('IRQ20','IRQ','Iraque',20,'Mohanad Ali','player'),
('CIV1','CIV','Costa do Marfim',1,'Team Logo','logo'),
('CIV2','CIV','Costa do Marfim',2,'Yahia Fofana','player'),
('CIV3','CIV','Costa do Marfim',3,'Ghislain Konan','player'),
('CIV4','CIV','Costa do Marfim',4,'Wilfried Singo','player'),
('CIV5','CIV','Costa do Marfim',5,'Odilon Kossounou','player'),
('CIV6','CIV','Costa do Marfim',6,'Evan Ndicka','player'),
('CIV7','CIV','Costa do Marfim',7,'Willy Boly','player'),
('CIV8','CIV','Costa do Marfim',8,'Emmanuel Agbadou','player'),
('CIV9','CIV','Costa do Marfim',9,'Ousmane Diomande','player'),
('CIV10','CIV','Costa do Marfim',10,'Franck Kessie','player'),
('CIV11','CIV','Costa do Marfim',11,'Seko Fofana','player'),
('CIV12','CIV','Costa do Marfim',12,'Ibrahim Sangare','player'),
('CIV13','CIV','Costa do Marfim',13,'Team Photo','photo'),
('CIV14','CIV','Costa do Marfim',14,'Jean-Philippe Gbamin','player'),
('CIV15','CIV','Costa do Marfim',15,'Amad Diallo','player'),
('CIV16','CIV','Costa do Marfim',16,'Sébastien Haller','player'),
('CIV17','CIV','Costa do Marfim',17,'Simon Adingra','player'),
('CIV18','CIV','Costa do Marfim',18,'Yan Diomande','player'),
('CIV19','CIV','Costa do Marfim',19,'Evann Guessand','player'),
('CIV20','CIV','Costa do Marfim',20,'Oumar Diakite','player'),
('JPN1','JPN','Japão',1,'Team Logo','logo'),
('JPN2','JPN','Japão',2,'Zion Suzuki','player'),
('JPN3','JPN','Japão',3,'Henry Heroki Mochizuki','player'),
('JPN4','JPN','Japão',4,'Ayumu Seko','player'),
('JPN5','JPN','Japão',5,'Junnosuke Suzuki','player'),
('JPN6','JPN','Japão',6,'Shogo Taniguchi','player'),
('JPN7','JPN','Japão',7,'Tsuyoshi Watanabe','player'),
('JPN8','JPN','Japão',8,'Kaishu Sano','player'),
('JPN9','JPN','Japão',9,'Yuki Soma','player'),
('JPN10','JPN','Japão',10,'Ao Tanaka','player'),
('JPN11','JPN','Japão',11,'Daichi Kamada','player'),
('JPN12','JPN','Japão',12,'Takefusa Kubo','player'),
('JPN13','JPN','Japão',13,'Team Photo','photo'),
('JPN14','JPN','Japão',14,'Ritsu Doan','player'),
('JPN15','JPN','Japão',15,'Keito Nakamura','player'),
('JPN16','JPN','Japão',16,'Takumi Minamino','player'),
('JPN17','JPN','Japão',17,'Shuto Machino','player'),
('JPN18','JPN','Japão',18,'Junya Ito','player'),
('JPN19','JPN','Japão',19,'Koki Ogawa','player'),
('JPN20','JPN','Japão',20,'Ayase Ueda','player'),
('JOR1','JOR','Jordânia',1,'Team Logo','logo'),
('JOR2','JOR','Jordânia',2,'Yazeed Abulaila','player'),
('JOR3','JOR','Jordânia',3,'Ihsan Haddad','player'),
('JOR4','JOR','Jordânia',4,'Mohammad Abu Hashish','player'),
('JOR5','JOR','Jordânia',5,'Yazan Al-Arab','player'),
('JOR6','JOR','Jordânia',6,'Abdallah Nasib','player'),
('JOR7','JOR','Jordânia',7,'Saleem Obaid','player'),
('JOR8','JOR','Jordânia',8,'Mohammad Abualnadi','player'),
('JOR9','JOR','Jordânia',9,'Ibrahim Saadeh','player'),
('JOR10','JOR','Jordânia',10,'Nizar Al-Rashdan','player'),
('JOR11','JOR','Jordânia',11,'Noor Al-Rawabdeh','player'),
('JOR12','JOR','Jordânia',12,'Mohannad Abu Taha','player'),
('JOR13','JOR','Jordânia',13,'Team Photo','photo'),
('JOR14','JOR','Jordânia',14,'Amer Jamous','player'),
('JOR15','JOR','Jordânia',15,'Musa Al-Taamari','player'),
('JOR16','JOR','Jordânia',16,'Yazan Al-Naimat','player'),
('JOR17','JOR','Jordânia',17,'Mahmoud Al-Mardi','player'),
('JOR18','JOR','Jordânia',18,'Ali Olwan','player'),
('JOR19','JOR','Jordânia',19,'Mohammad Abu Zrayq','player'),
('JOR20','JOR','Jordânia',20,'Ibrahim Sabra','player'),
('MEX1','MEX','México',1,'Team Logo','logo'),
('MEX2','MEX','México',2,'Luis Malagón','player'),
('MEX3','MEX','México',3,'Johan Vasquez','player'),
('MEX4','MEX','México',4,'Jorge Sánchez','player'),
('MEX5','MEX','México',5,'Cesar Montes','player'),
('MEX6','MEX','México',6,'Jesus Gallardo','player'),
('MEX7','MEX','México',7,'Israel Reyes','player'),
('MEX8','MEX','México',8,'Diego Lainez','player'),
('MEX9','MEX','México',9,'Carlos Rodriguez','player'),
('MEX10','MEX','México',10,'Edson Alvarez','player'),
('MEX11','MEX','México',11,'Orbelin Pineda','player'),
('MEX12','MEX','México',12,'Marcel Ruiz','player'),
('MEX13','MEX','México',13,'Team Photo','photo'),
('MEX14','MEX','México',14,'Érick Sánchez','player'),
('MEX15','MEX','México',15,'Hirving Lozano','player'),
('MEX16','MEX','México',16,'Santiago Giménez','player'),
('MEX17','MEX','México',17,'Raúl Jiménez','player'),
('MEX18','MEX','México',18,'Alexis Vega','player'),
('MEX19','MEX','México',19,'Roberto Alvarado','player'),
('MEX20','MEX','México',20,'Cesar Huerta','player'),
('MAR1','MAR','Marrocos',1,'Team Logo','logo'),
('MAR2','MAR','Marrocos',2,'Yassine Bounou','player'),
('MAR3','MAR','Marrocos',3,'Munir El Kajoui','player'),
('MAR4','MAR','Marrocos',4,'Achraf Hakimi','player'),
('MAR5','MAR','Marrocos',5,'Noussair Mazraoui','player'),
('MAR6','MAR','Marrocos',6,'Nayef Aguerd','player'),
('MAR7','MAR','Marrocos',7,'Roman Saiss','player'),
('MAR8','MAR','Marrocos',8,'Jawad El Yamio','player'),
('MAR9','MAR','Marrocos',9,'Adam Masina','player'),
('MAR10','MAR','Marrocos',10,'Sofyan Amrabat','player'),
('MAR11','MAR','Marrocos',11,'Azzedine Ounahi','player'),
('MAR12','MAR','Marrocos',12,'Eliesse Ben Seghir','player'),
('MAR13','MAR','Marrocos',13,'Team Photo','photo'),
('MAR14','MAR','Marrocos',14,'Bilal El Khannouss','player'),
('MAR15','MAR','Marrocos',15,'Ismael Saibari','player'),
('MAR16','MAR','Marrocos',16,'Youssef En-Nesyri','player'),
('MAR17','MAR','Marrocos',17,'Abde Ezzalzouli','player'),
('MAR18','MAR','Marrocos',18,'Soufiane Rahimi','player'),
('MAR19','MAR','Marrocos',19,'Brahim Diaz','player'),
('MAR20','MAR','Marrocos',20,'Ayoub El Kaabi','player'),
('NED1','NED','Holanda',1,'Team Logo','logo'),
('NED2','NED','Holanda',2,'Bart Verbruggen','player'),
('NED3','NED','Holanda',3,'Virgil van Dijk','player'),
('NED4','NED','Holanda',4,'Micky van de Ven','player'),
('NED5','NED','Holanda',5,'Jurrien Timber','player'),
('NED6','NED','Holanda',6,'Denzel Dumfries','player'),
('NED7','NED','Holanda',7,'Nathan Aké','player'),
('NED8','NED','Holanda',8,'Jeremie Frimpong','player'),
('NED9','NED','Holanda',9,'Jan Paul van Hecke','player'),
('NED10','NED','Holanda',10,'Tijjani Reijnders','player'),
('NED11','NED','Holanda',11,'Ryan Gravenberch','player'),
('NED12','NED','Holanda',12,'Teun Koopmeiners','player'),
('NED13','NED','Holanda',13,'Team Photo','photo'),
('NED14','NED','Holanda',14,'Frenkie de Jong','player'),
('NED15','NED','Holanda',15,'Xavi Simons','player'),
('NED16','NED','Holanda',16,'Justin Kluivert','player'),
('NED17','NED','Holanda',17,'Memphis Depay','player'),
('NED18','NED','Holanda',18,'Donyell Malen','player'),
('NED19','NED','Holanda',19,'Wout Weghorst','player'),
('NED20','NED','Holanda',20,'Cody Gakpo','player'),
('NZL1','NZL','Nova Zelândia',1,'Team Logo','logo'),
('NZL2','NZL','Nova Zelândia',2,'Max Crocombe Payne','player'),
('NZL3','NZL','Nova Zelândia',3,'Alex Paulsen','player'),
('NZL4','NZL','Nova Zelândia',4,'Michael Boxall','player'),
('NZL5','NZL','Nova Zelândia',5,'Liberato Cacace','player'),
('NZL6','NZL','Nova Zelândia',6,'Tim Payne','player'),
('NZL7','NZL','Nova Zelândia',7,'Tyler Bindon','player'),
('NZL8','NZL','Nova Zelândia',8,'Francis de Vries','player'),
('NZL9','NZL','Nova Zelândia',9,'Finn Surman','player'),
('NZL10','NZL','Nova Zelândia',10,'Joe Bell','player'),
('NZL11','NZL','Nova Zelândia',11,'Sarpreet Singh','player'),
('NZL12','NZL','Nova Zelândia',12,'Ryan Thomas','player'),
('NZL13','NZL','Nova Zelândia',13,'Team Photo','photo'),
('NZL14','NZL','Nova Zelândia',14,'Matthew Garbett','player'),
('NZL15','NZL','Nova Zelândia',15,'Marko Stamenić','player'),
('NZL16','NZL','Nova Zelândia',16,'Ben Old','player'),
('NZL17','NZL','Nova Zelândia',17,'Chris Wood','player'),
('NZL18','NZL','Nova Zelândia',18,'Elijah Just','player'),
('NZL19','NZL','Nova Zelândia',19,'Callum McCowatt','player'),
('NZL20','NZL','Nova Zelândia',20,'Kosta Barbarouses','player'),
('NOR1','NOR','Noruega',1,'Team Logo','logo'),
('NOR2','NOR','Noruega',2,'Orjan Nyland','player'),
('NOR3','NOR','Noruega',3,'Julian Ryerson','player'),
('NOR4','NOR','Noruega',4,'Leo Ostigård','player'),
('NOR5','NOR','Noruega',5,'Kristoffer Vassbakk Ajer','player'),
('NOR6','NOR','Noruega',6,'Marcus Holmgren Pedersen','player'),
('NOR7','NOR','Noruega',7,'David Møller Wolfe','player'),
('NOR8','NOR','Noruega',8,'Torbjørn Heggem','player'),
('NOR9','NOR','Noruega',9,'Morten Thorsby','player'),
('NOR10','NOR','Noruega',10,'Martin Ødegaard','player'),
('NOR11','NOR','Noruega',11,'Sander Berge','player'),
('NOR12','NOR','Noruega',12,'Andreas Schjelderup','player'),
('NOR13','NOR','Noruega',13,'Team Photo','photo'),
('NOR14','NOR','Noruega',14,'Patrick Berg','player'),
('NOR15','NOR','Noruega',15,'Erling Haaland','player'),
('NOR16','NOR','Noruega',16,'Alexander Sørloth','player'),
('NOR17','NOR','Noruega',17,'Aron Dønnum','player'),
('NOR18','NOR','Noruega',18,'Jorgen Strand Larsen','player'),
('NOR19','NOR','Noruega',19,'Antonio Nusa','player'),
('NOR20','NOR','Noruega',20,'Oscar Bobb','player'),
('PAN1','PAN','Panamá',1,'Team Logo','logo'),
('PAN2','PAN','Panamá',2,'Orlando Mosquera','player'),
('PAN3','PAN','Panamá',3,'Luis Mejia','player'),
('PAN4','PAN','Panamá',4,'Fidel Escobar','player'),
('PAN5','PAN','Panamá',5,'Andres Andrade','player'),
('PAN6','PAN','Panamá',6,'Michael Amir Murillo','player'),
('PAN7','PAN','Panamá',7,'Eric Davis','player'),
('PAN8','PAN','Panamá',8,'Jose Cordoba','player'),
('PAN9','PAN','Panamá',9,'Cesar Blackman','player'),
('PAN10','PAN','Panamá',10,'Cristian Martinez','player'),
('PAN11','PAN','Panamá',11,'Aníbal Godoy','player'),
('PAN12','PAN','Panamá',12,'Adalberto Carrasquilla','player'),
('PAN13','PAN','Panamá',13,'Team Photo','photo'),
('PAN14','PAN','Panamá',14,'Édgar Bárcenas','player'),
('PAN15','PAN','Panamá',15,'Carlos Harvey','player'),
('PAN16','PAN','Panamá',16,'Ismael Díaz','player'),
('PAN17','PAN','Panamá',17,'Jose Fajardo','player'),
('PAN18','PAN','Panamá',18,'Cecilio Waterman','player'),
('PAN19','PAN','Panamá',19,'Jose Luiz Rodriguez','player'),
('PAN20','PAN','Panamá',20,'Alberto Quintero','player'),
('PAR1','PAR','Paraguai',1,'Team Logo','logo'),
('PAR2','PAR','Paraguai',2,'Roberto Fernandez','player'),
('PAR3','PAR','Paraguai',3,'Orlando Gill','player'),
('PAR4','PAR','Paraguai',4,'Gustavo Gomez','player'),
('PAR5','PAR','Paraguai',5,'Fabián Balbuena','player'),
('PAR6','PAR','Paraguai',6,'Juan José Cáceres','player'),
('PAR7','PAR','Paraguai',7,'Omar Alderete','player'),
('PAR8','PAR','Paraguai',8,'Junior Alonso','player'),
('PAR9','PAR','Paraguai',9,'Mathías Villasanti','player'),
('PAR10','PAR','Paraguai',10,'Diego Gomez','player'),
('PAR11','PAR','Paraguai',11,'Damián Bobadilla','player'),
('PAR12','PAR','Paraguai',12,'Andres Cubas','player'),
('PAR13','PAR','Paraguai',13,'Team Photo','photo'),
('PAR14','PAR','Paraguai',14,'Matias Galarza Fonda','player'),
('PAR15','PAR','Paraguai',15,'Julio Enciso','player'),
('PAR16','PAR','Paraguai',16,'Alejandro Romero Gamarra','player'),
('PAR17','PAR','Paraguai',17,'Miguel Almirón','player'),
('PAR18','PAR','Paraguai',18,'Ramon Sosa','player'),
('PAR19','PAR','Paraguai',19,'Angel Romero','player'),
('PAR20','PAR','Paraguai',20,'Antonio Sanabria','player'),
('POR1','POR','Portugal',1,'Team Logo','logo'),
('POR2','POR','Portugal',2,'Diogo Costa','player'),
('POR3','POR','Portugal',3,'Jose Sa','player'),
('POR4','POR','Portugal',4,'Ruben Dias','player'),
('POR5','POR','Portugal',5,'João Cancelo','player'),
('POR6','POR','Portugal',6,'Diogo Dalot','player'),
('POR7','POR','Portugal',7,'Nuno Mendes','player'),
('POR8','POR','Portugal',8,'Gonçalo Inácio','player'),
('POR9','POR','Portugal',9,'Bernardo Silva','player'),
('POR10','POR','Portugal',10,'Bruno Fernandes','player'),
('POR11','POR','Portugal',11,'Ruben Neves','player'),
('POR12','POR','Portugal',12,'Vitinha','player'),
('POR13','POR','Portugal',13,'Team Photo','photo'),
('POR14','POR','Portugal',14,'João Neves','player'),
('POR15','POR','Portugal',15,'Cristiano Ronaldo','player'),
('POR16','POR','Portugal',16,'Francisco Trincao','player'),
('POR17','POR','Portugal',17,'João Felix','player'),
('POR18','POR','Portugal',18,'Gonçalo Ramos','player'),
('POR19','POR','Portugal',19,'Pedro Neto','player'),
('POR20','POR','Portugal',20,'Rafael Leão','player'),
('QAT1','QAT','Catar',1,'Team Logo','logo'),
('QAT2','QAT','Catar',2,'Meshaal Barsham','player'),
('QAT3','QAT','Catar',3,'Sultan Albrake','player'),
('QAT4','QAT','Catar',4,'Lucas Mendes','player'),
('QAT5','QAT','Catar',5,'Homam Ahmed','player'),
('QAT6','QAT','Catar',6,'Boualem Khoukhi','player'),
('QAT7','QAT','Catar',7,'Pedro Miguel','player'),
('QAT8','QAT','Catar',8,'Tarek Salman','player'),
('QAT9','QAT','Catar',9,'Mohamed Al-Mannai','player'),
('QAT10','QAT','Catar',10,'Karim Boudiaf','player'),
('QAT11','QAT','Catar',11,'Assim Madibo','player'),
('QAT12','QAT','Catar',12,'Ahmed Fatehi','player'),
('QAT13','QAT','Catar',13,'Team Photo','photo'),
('QAT14','QAT','Catar',14,'Mohammed Waad','player'),
('QAT15','QAT','Catar',15,'Abdulaziz Hatem','player'),
('QAT16','QAT','Catar',16,'Hassan Al-Haydos','player'),
('QAT17','QAT','Catar',17,'Edmilson Junior','player'),
('QAT18','QAT','Catar',18,'Akram Hassan Afif','player'),
('QAT19','QAT','Catar',19,'Ahmed Al Ganehi','player'),
('QAT20','QAT','Catar',20,'Almoez Ali','player'),
('KSA1','KSA','Arábia Saudita',1,'Team Logo','logo'),
('KSA2','KSA','Arábia Saudita',2,'Nawaf Alaqidi','player'),
('KSA3','KSA','Arábia Saudita',3,'Abdulrahman Al-Sanbi','player'),
('KSA4','KSA','Arábia Saudita',4,'Saud Abdulhamid','player'),
('KSA5','KSA','Arábia Saudita',5,'Nawaf Bouwashl','player'),
('KSA6','KSA','Arábia Saudita',6,'Jihad Thakri','player'),
('KSA7','KSA','Arábia Saudita',7,'Moteb Al-Harbi','player'),
('KSA8','KSA','Arábia Saudita',8,'Hassan Altambakti','player'),
('KSA9','KSA','Arábia Saudita',9,'Musab Aljuwayr','player'),
('KSA10','KSA','Arábia Saudita',10,'Ziyad Aljohani','player'),
('KSA11','KSA','Arábia Saudita',11,'Abdullah Alkhaibari','player'),
('KSA12','KSA','Arábia Saudita',12,'Nasser Aldawsari','player'),
('KSA13','KSA','Arábia Saudita',13,'Team Photo','photo'),
('KSA14','KSA','Arábia Saudita',14,'Saleh Abu Alshamat','player'),
('KSA15','KSA','Arábia Saudita',15,'Marwan Alsahafi','player'),
('KSA16','KSA','Arábia Saudita',16,'Salem Aldawsari','player'),
('KSA17','KSA','Arábia Saudita',17,'Abdulrahman Al-Aboud','player'),
('KSA18','KSA','Arábia Saudita',18,'Feras Akbrikan','player'),
('KSA19','KSA','Arábia Saudita',19,'Saleh Alshehri','player'),
('KSA20','KSA','Arábia Saudita',20,'Abdullah Al-Hamdan','player'),
('SCO1','SCO','Escócia',1,'Team Logo','logo'),
('SCO2','SCO','Escócia',2,'Angus Gunn','player'),
('SCO3','SCO','Escócia',3,'Jack Hendry','player'),
('SCO4','SCO','Escócia',4,'Kieran Tierney','player'),
('SCO5','SCO','Escócia',5,'Aaron Hickey','player'),
('SCO6','SCO','Escócia',6,'Andrew Robertson','player'),
('SCO7','SCO','Escócia',7,'Scott McKenna','player'),
('SCO8','SCO','Escócia',8,'John Souttar','player'),
('SCO9','SCO','Escócia',9,'Anthony Ralston','player'),
('SCO10','SCO','Escócia',10,'Grant Hanley','player'),
('SCO11','SCO','Escócia',11,'Scott McTominay','player'),
('SCO12','SCO','Escócia',12,'Billy Gilmour','player'),
('SCO13','SCO','Escócia',13,'Team Photo','photo'),
('SCO14','SCO','Escócia',14,'Lewis Ferguson','player'),
('SCO15','SCO','Escócia',15,'Ryan Christie','player'),
('SCO16','SCO','Escócia',16,'Kenny McLean','player'),
('SCO17','SCO','Escócia',17,'John McGinn','player'),
('SCO18','SCO','Escócia',18,'Lyndon Dykes','player'),
('SCO19','SCO','Escócia',19,'Che Adams','player'),
('SCO20','SCO','Escócia',20,'Ben Gannon-Doak','player'),
('SEN1','SEN','Senegal',1,'Team Logo','logo'),
('SEN2','SEN','Senegal',2,'Edouard Mendy','player'),
('SEN3','SEN','Senegal',3,'Yehvann Diouf','player'),
('SEN4','SEN','Senegal',4,'Moussa Niakhaté','player'),
('SEN5','SEN','Senegal',5,'Abdoulaye Seck','player'),
('SEN6','SEN','Senegal',6,'Ismail Jakobs','player'),
('SEN7','SEN','Senegal',7,'El Hadji Malick Diouf','player'),
('SEN8','SEN','Senegal',8,'Kalidou Koulibaly','player'),
('SEN9','SEN','Senegal',9,'Idrissa Gana Gueye','player'),
('SEN10','SEN','Senegal',10,'Pape Matar Sarr','player'),
('SEN11','SEN','Senegal',11,'Pape Gueye','player'),
('SEN12','SEN','Senegal',12,'Habib Diarra','player'),
('SEN13','SEN','Senegal',13,'Team Photo','photo'),
('SEN14','SEN','Senegal',14,'Lamine Camara','player'),
('SEN15','SEN','Senegal',15,'Sadio Mane','player'),
('SEN16','SEN','Senegal',16,'Ismaïla Sarr','player'),
('SEN17','SEN','Senegal',17,'Boulaye Dia','player'),
('SEN18','SEN','Senegal',18,'Iliman Ndiaye','player'),
('SEN19','SEN','Senegal',19,'Nicolas Jackson','player'),
('SEN20','SEN','Senegal',20,'Krepin Diatta','player'),
('RSA1','RSA','África do Sul',1,'Team Logo','logo'),
('RSA2','RSA','África do Sul',2,'Ronwen Williams','player'),
('RSA3','RSA','África do Sul',3,'Sipho Chaine','player'),
('RSA4','RSA','África do Sul',4,'Aubrey Modiba','player'),
('RSA5','RSA','África do Sul',5,'Samukele Kabini','player'),
('RSA6','RSA','África do Sul',6,'Mbekezeli Mbokazi','player'),
('RSA7','RSA','África do Sul',7,'Khulumani Ndamane','player'),
('RSA8','RSA','África do Sul',8,'Siyabonga Ngezana','player'),
('RSA9','RSA','África do Sul',9,'Khuliso Mudau','player'),
('RSA10','RSA','África do Sul',10,'Nkosinathi Sibisi','player'),
('RSA11','RSA','África do Sul',11,'Teboho Mokoena','player'),
('RSA12','RSA','África do Sul',12,'Thalente Mbatha','player'),
('RSA13','RSA','África do Sul',13,'Team Photo','photo'),
('RSA14','RSA','África do Sul',14,'Bathasi Aubaas','player'),
('RSA15','RSA','África do Sul',15,'Yaya Sithole','player'),
('RSA16','RSA','África do Sul',16,'Sipho Mbule','player'),
('RSA17','RSA','África do Sul',17,'Lyle Foster','player'),
('RSA18','RSA','África do Sul',18,'Iqraam Rayners','player'),
('RSA19','RSA','África do Sul',19,'Mohau Nkota','player'),
('RSA20','RSA','África do Sul',20,'Oswin Appollis','player'),
('KOR1','KOR','Coreia do Sul',1,'Team Logo','logo'),
('KOR2','KOR','Coreia do Sul',2,'Hyeon-woo Jo','player'),
('KOR3','KOR','Coreia do Sul',3,'Seung-Gyu Kim','player'),
('KOR4','KOR','Coreia do Sul',4,'Min-jae Kim','player'),
('KOR5','KOR','Coreia do Sul',5,'Yu-min Cho','player'),
('KOR6','KOR','Coreia do Sul',6,'Young-woo Seol','player'),
('KOR7','KOR','Coreia do Sul',7,'Han-beom Lee','player'),
('KOR8','KOR','Coreia do Sul',8,'Tae-seok Lee','player'),
('KOR9','KOR','Coreia do Sul',9,'Myung-jae Lee','player'),
('KOR10','KOR','Coreia do Sul',10,'Jae-sung Lee','player'),
('KOR11','KOR','Coreia do Sul',11,'In-beom Hwang','player'),
('KOR12','KOR','Coreia do Sul',12,'Kang-in Lee','player'),
('KOR13','KOR','Coreia do Sul',13,'Team Photo','photo'),
('KOR14','KOR','Coreia do Sul',14,'Seung-ho Paik','player'),
('KOR15','KOR','Coreia do Sul',15,'Jens Castrop','player'),
('KOR16','KOR','Coreia do Sul',16,'Dongg-yeong Lee','player'),
('KOR17','KOR','Coreia do Sul',17,'Gue-sung Cho','player'),
('KOR18','KOR','Coreia do Sul',18,'Heung-min Son','player'),
('KOR19','KOR','Coreia do Sul',19,'Hee-chan Hwang','player'),
('KOR20','KOR','Coreia do Sul',20,'Hyeon-Gyu Oh','player'),
('ESP1','ESP','Espanha',1,'Team Logo','logo'),
('ESP2','ESP','Espanha',2,'Unai Simon','player'),
('ESP3','ESP','Espanha',3,'Robin Le Normand','player'),
('ESP4','ESP','Espanha',4,'Aymeric Laporte','player'),
('ESP5','ESP','Espanha',5,'Dean Huijsen','player'),
('ESP6','ESP','Espanha',6,'Pedro Porro','player'),
('ESP7','ESP','Espanha',7,'Dani Carvajal','player'),
('ESP8','ESP','Espanha',8,'Marc Cucurella','player'),
('ESP9','ESP','Espanha',9,'Martín Zubimendi','player'),
('ESP10','ESP','Espanha',10,'Rodri','player'),
('ESP11','ESP','Espanha',11,'Pedri','player'),
('ESP12','ESP','Espanha',12,'Fabian Ruiz','player'),
('ESP13','ESP','Espanha',13,'Team Photo','photo'),
('ESP14','ESP','Espanha',14,'Mikel Merino','player'),
('ESP15','ESP','Espanha',15,'Lamine Yamal','player'),
('ESP16','ESP','Espanha',16,'Dani Olmo','player'),
('ESP17','ESP','Espanha',17,'Nico Williams','player'),
('ESP18','ESP','Espanha',18,'Ferran Torres','player'),
('ESP19','ESP','Espanha',19,'Álvaro Morata','player'),
('ESP20','ESP','Espanha',20,'Mikel Oyarzabal','player'),
('SWE1','SWE','Suécia',1,'Team Logo','logo'),
('SWE2','SWE','Suécia',2,'Victor Johansson','player'),
('SWE3','SWE','Suécia',3,'Isak Hien','player'),
('SWE4','SWE','Suécia',4,'Gabriel Gudmundsson','player'),
('SWE5','SWE','Suécia',5,'Emil Holm','player'),
('SWE6','SWE','Suécia',6,'Victor Nilsson Lindelöf','player'),
('SWE7','SWE','Suécia',7,'Gustaf Lagerbielke','player'),
('SWE8','SWE','Suécia',8,'Lucas Bergvall','player'),
('SWE9','SWE','Suécia',9,'Hugo Larsson','player'),
('SWE10','SWE','Suécia',10,'Jesper Karlström','player'),
('SWE11','SWE','Suécia',11,'Yasin Ayari','player'),
('SWE12','SWE','Suécia',12,'Mattias Svanberg','player'),
('SWE13','SWE','Suécia',13,'Team Photo','photo'),
('SWE14','SWE','Suécia',14,'Daniel Svensson','player'),
('SWE15','SWE','Suécia',15,'Ken Sema','player'),
('SWE16','SWE','Suécia',16,'Roony Bardghji','player'),
('SWE17','SWE','Suécia',17,'Dejan Kulusevski','player'),
('SWE18','SWE','Suécia',18,'Anthony Elanga','player'),
('SWE19','SWE','Suécia',19,'Alexander Isak','player'),
('SWE20','SWE','Suécia',20,'Viktor Gyökeres','player'),
('SUI1','SUI','Suíça',1,'Team Logo','logo'),
('SUI2','SUI','Suíça',2,'Gregor Kobel','player'),
('SUI3','SUI','Suíça',3,'Yvon Mvogo','player'),
('SUI4','SUI','Suíça',4,'Manuel Akanji','player'),
('SUI5','SUI','Suíça',5,'Ricardo Rodriguez','player'),
('SUI6','SUI','Suíça',6,'Nico Elvedi','player'),
('SUI7','SUI','Suíça',7,'Aurèle Amenda','player'),
('SUI8','SUI','Suíça',8,'Silvan Widmer','player'),
('SUI9','SUI','Suíça',9,'Granit Xhaka','player'),
('SUI10','SUI','Suíça',10,'Denis Zakaria','player'),
('SUI11','SUI','Suíça',11,'Remo Freuler','player'),
('SUI12','SUI','Suíça',12,'Fabian Rieder','player'),
('SUI13','SUI','Suíça',13,'Team Photo','photo'),
('SUI14','SUI','Suíça',14,'Ardon Jashari','player'),
('SUI15','SUI','Suíça',15,'Johan Manzambi','player'),
('SUI16','SUI','Suíça',16,'Michel Aebischer','player'),
('SUI17','SUI','Suíça',17,'Breel Embolo','player'),
('SUI18','SUI','Suíça',18,'Ruben Vargas','player'),
('SUI19','SUI','Suíça',19,'Dan Ndoye','player'),
('SUI20','SUI','Suíça',20,'Zeki Amdouni','player'),
('TUN1','TUN','Tunísia',1,'Team Logo','logo'),
('TUN2','TUN','Tunísia',2,'Bechir Ben Said','player'),
('TUN3','TUN','Tunísia',3,'Aymen Dahmen','player'),
('TUN4','TUN','Tunísia',4,'Yan Valery','player'),
('TUN5','TUN','Tunísia',5,'Montassar Talbi','player'),
('TUN6','TUN','Tunísia',6,'Yassine Meriah','player'),
('TUN7','TUN','Tunísia',7,'Ali Abdi','player'),
('TUN8','TUN','Tunísia',8,'Dylan Bronn','player'),
('TUN9','TUN','Tunísia',9,'Ellyes Skhiri','player'),
('TUN10','TUN','Tunísia',10,'Aissa Laidouni','player'),
('TUN11','TUN','Tunísia',11,'Ferjani Sassi','player'),
('TUN12','TUN','Tunísia',12,'Mohamed Ali Ben Romdhane','player'),
('TUN13','TUN','Tunísia',13,'Team Photo','photo'),
('TUN14','TUN','Tunísia',14,'Hannibal Mejbri','player'),
('TUN15','TUN','Tunísia',15,'Elias Achouri','player'),
('TUN16','TUN','Tunísia',16,'Elias Saad','player'),
('TUN17','TUN','Tunísia',17,'Hazem Mastouri','player'),
('TUN18','TUN','Tunísia',18,'Ismael Gharbi','player'),
('TUN19','TUN','Tunísia',19,'Sayfallah Ltaief','player'),
('TUN20','TUN','Tunísia',20,'Naim Sliti','player'),
('TUR1','TUR','Turquia',1,'Team Logo','logo'),
('TUR2','TUR','Turquia',2,'Ugurcan Cakir','player'),
('TUR3','TUR','Turquia',3,'Mert Muldur','player'),
('TUR4','TUR','Turquia',4,'Zeki Celik','player'),
('TUR5','TUR','Turquia',5,'Abdulkerim Bardakci','player'),
('TUR6','TUR','Turquia',6,'Caglar Soyuncu','player'),
('TUR7','TUR','Turquia',7,'Merih Demiral','player'),
('TUR8','TUR','Turquia',8,'Ferdi Kadioglu','player'),
('TUR9','TUR','Turquia',9,'Kaan Ayhan','player'),
('TUR10','TUR','Turquia',10,'Ismail Yuksek','player'),
('TUR11','TUR','Turquia',11,'Hakan Calhanoglu','player'),
('TUR12','TUR','Turquia',12,'Orkun Kokcu','player'),
('TUR13','TUR','Turquia',13,'Team Photo','photo'),
('TUR14','TUR','Turquia',14,'Arda Guler','player'),
('TUR15','TUR','Turquia',15,'Irfan Can Kahveci','player'),
('TUR16','TUR','Turquia',16,'Yunus Akgun','player'),
('TUR17','TUR','Turquia',17,'Can Uzun','player'),
('TUR18','TUR','Turquia',18,'Baris Alper Yilmaz','player'),
('TUR19','TUR','Turquia',19,'Kerem Akturkoglu','player'),
('TUR20','TUR','Turquia',20,'Kenan Yildiz','player'),
('URU1','URU','Uruguai',1,'Team Logo','logo'),
('URU2','URU','Uruguai',2,'Sergio Rochet','player'),
('URU3','URU','Uruguai',3,'Santiago Mele','player'),
('URU4','URU','Uruguai',4,'Ronald Araujo','player'),
('URU5','URU','Uruguai',5,'José María Giménez','player'),
('URU6','URU','Uruguai',6,'Sebastian Caceres','player'),
('URU7','URU','Uruguai',7,'Mathias Olivera','player'),
('URU8','URU','Uruguai',8,'Guillermo Varela','player'),
('URU9','URU','Uruguai',9,'Nahitan Nandez','player'),
('URU10','URU','Uruguai',10,'Federico Valverde','player'),
('URU11','URU','Uruguai',11,'Giorgian De Arrascaeta','player'),
('URU12','URU','Uruguai',12,'Rodrigo Bentancur','player'),
('URU13','URU','Uruguai',13,'Team Photo','photo'),
('URU14','URU','Uruguai',14,'Manuel Ugarte','player'),
('URU15','URU','Uruguai',15,'Nicolás de la Cruz','player'),
('URU16','URU','Uruguai',16,'Maxi Araujo','player'),
('URU17','URU','Uruguai',17,'Darwin Núñez','player'),
('URU18','URU','Uruguai',18,'Federico Viñas','player'),
('URU19','URU','Uruguai',19,'Rodrigo Aguirre','player'),
('URU20','URU','Uruguai',20,'Facundo Pellistri','player'),
('USA1','USA','Estados Unidos',1,'Team Logo','logo'),
('USA2','USA','Estados Unidos',2,'Math Freese','player'),
('USA3','USA','Estados Unidos',3,'Chris Richards','player'),
('USA4','USA','Estados Unidos',4,'Tim Ream','player'),
('USA5','USA','Estados Unidos',5,'Mark McKenzie','player'),
('USA6','USA','Estados Unidos',6,'Alex Freeman','player'),
('USA7','USA','Estados Unidos',7,'Antonee Robinson','player'),
('USA8','USA','Estados Unidos',8,'Tyler Adams','player'),
('USA9','USA','Estados Unidos',9,'Tanner Tessmann','player'),
('USA10','USA','Estados Unidos',10,'Weston McKennie','player'),
('USA11','USA','Estados Unidos',11,'Christian Roldan','player'),
('USA12','USA','Estados Unidos',12,'Timothy Weah','player'),
('USA13','USA','Estados Unidos',13,'Team Photo','photo'),
('USA14','USA','Estados Unidos',14,'Diego Luna','player'),
('USA15','USA','Estados Unidos',15,'Malik Tillman','player'),
('USA16','USA','Estados Unidos',16,'Christian Pulisic','player'),
('USA17','USA','Estados Unidos',17,'Brenden Aaronson','player'),
('USA18','USA','Estados Unidos',18,'Ricardo Pepi','player'),
('USA19','USA','Estados Unidos',19,'Haji Wright','player'),
('USA20','USA','Estados Unidos',20,'Folarin Balogun','player'),
('UZB1','UZB','Uzbequistão',1,'Team Logo','logo'),
('UZB2','UZB','Uzbequistão',2,'Utkir Yusupov','player'),
('UZB3','UZB','Uzbequistão',3,'Farrukh Savfiev','player'),
('UZB4','UZB','Uzbequistão',4,'Sherzod Nasrullaev','player'),
('UZB5','UZB','Uzbequistão',5,'Umar Eshmurodov','player'),
('UZB6','UZB','Uzbequistão',6,'Husniddin Aliqulov','player'),
('UZB7','UZB','Uzbequistão',7,'Rustamjon Ashurmatov','player'),
('UZB8','UZB','Uzbequistão',8,'Khojiakbar Alijonov','player'),
('UZB9','UZB','Uzbequistão',9,'Abdukodir Khusanov','player'),
('UZB10','UZB','Uzbequistão',10,'Odiljon Hamrobekov','player'),
('UZB11','UZB','Uzbequistão',11,'Otabek Shukurov','player'),
('UZB12','UZB','Uzbequistão',12,'Jamshid Iskanderov','player'),
('UZB13','UZB','Uzbequistão',13,'Team Photo','photo'),
('UZB14','UZB','Uzbequistão',14,'Azizbek Turgunboev','player'),
('UZB15','UZB','Uzbequistão',15,'Khojimat Erkinov','player'),
('UZB16','UZB','Uzbequistão',16,'Eldor Shomurodov','player'),
('UZB17','UZB','Uzbequistão',17,'Oston Urunov','player'),
('UZB18','UZB','Uzbequistão',18,'Jaloliddin Masharipov','player'),
('UZB19','UZB','Uzbequistão',19,'Igor Sergeev','player'),
('UZB20','UZB','Uzbequistão',20,'Abbosbek Fayzullaev','player')
on conflict (id) do update set
  team_code=excluded.team_code, team_name=excluded.team_name,
  number=excluded.number, name=excluded.name, kind=excluded.kind;
